spring:
  application:
    name: LiteSkin
  config:
    import: classpath:liteskin.yaml
  datasource:
    url: "jdbc:mysql://${database.host}:${database.port}/${database.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai"
    username: ${database.username}
    password: ${database.password}
server:
  port: 8080


# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'LiteSkin'
      paths-to-match: '/**'
      packages-to-scan: cn.xiuxius.mc.liteskin.controller
  default-flat-param-object: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
